spring.application.name=todo-list-api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://postgres:5432/tododb
spring.datasource.username=todo
spring.datasource.password=secret

jwt.secret=${JWT_SECRET:ad6a5e3ec3429a7b426f157421a8c86644be3463fe2c914c4199037ff66c7e50}